### ISSUE TITLE
incorrect tagging of contractions

### ISSUE THREAD

**Issue by jenni-divvito** [winkjs/wink-pos-tagger#24]
Hello,

When tagging a contraction, the first part of the contraction does not seem to be properly handled at the moment in some common cases. For example when tagging the sentence "I can't believe you", we get the result:

`[{"value":"I","tag":"word","normal":"i","pos":"PRP"},{"value":"ca","tag":"word","normal":"ca","pos":"NN","lemma":"ca"},{"value":"not","tag":"word","normal":"not","pos":"RB"},{"value":"believe","tag":"word","normal":"believe","pos":"VB","lemma":"believe"},{"value":"you","tag":"word","normal":"you","pos":"PRP"}]`

"n't" is properly normalized to "not" and tagged as RB, however, the first part is not properly dealt with as "can" - which I believe should be tagged as a modal (MD).

the same seems to hold true for "won't", although "shouldn't" and "don't" seem to be properly tagged (assumedly because the naive transformation of removing the character before the apostrophe leaves them with the correct word).

**Comment by rachnachakraborty** [comment]
Hello @chris-divvito ,

Thank you for documenting and highlighting the issue.

The apostrophe and contraction issues, including this one are in our radar for next release due sometime in early June 2018. 

In the meantime, we request you to use `updateLexicon()` api to work around this issue. You can define pos tags for "ca" and "wo" as `[ 'MD' ]`. Also, we recommend that you define "'s"(apostrophe) as `[ 'POS', 'VBZ' ]`. With this you will be able to properly pos tag sentences like "Then's the time to time the time flies"

Please refer to the snippet below:
```javascript
var tagger = require( 'wink-pos-tagger' )();
var myLex = Object.create( null );
myLex[ '\'s' ] = [ 'POS', 'VBZ' ];
myLex[ 'ca' ] = [ 'MD' ];
myLex[ 'wo' ] = [ 'MD' ];
tagger.updateLexicon( myLex );
console.log( tagger.tagSentence( 'Then\'s the time to time the time flies' ) );
console.log( tagger.tagSentence( 'I won\'t believe you' ) );
```
This will produce the following output:

```javascript
[ { value: 'Then', tag: 'word', normal: 'then', pos: 'RB' },
  { value: '\'s',  tag: 'word', normal: '\'s', pos: 'VBZ', lemma: '\'s' },
  { value: 'the', tag: 'word', normal: 'the', pos: 'DT' },
  { value: 'time', tag: 'word', normal: 'time',  pos: 'NN', lemma: 'time' },
  { value: 'to', tag: 'word', normal: 'to', pos: 'TO' },
  { value: 'time', tag: 'word', normal: 'time'  pos: 'VB', lemma: 'time' },
  { value: 'the', tag: 'word', normal: 'the', pos: 'DT' },
  { value: 'time', tag: 'word', normal: 'time', pos: 'NN', lemma: 'time' },
  { value: 'flies', tag: 'word', normal: 'flies', pos: 'VBZ', lemma: 'fly' } ]
[ { value: 'I', tag: 'word', normal: 'i', pos: 'PRP' },
  { value: 'wo', tag: 'word', normal: 'wo', pos: 'MD', lemma: 'wo' },
  { value: 'not', tag: 'word', normal: 'not', pos: 'RB' },
  { value: 'believe', tag: 'word', normal: 'believe', pos: 'VB', lemma: 'believe' },
  { value: 'you', tag: 'word', normal: 'you', pos: 'PRP' } ]
```
Hope it addresses this issue.

Best,

**Comment by jenni-divvito** [comment]
Thanks very much for the clarification @rachnachakraborty - I can confirm that the suggested workaround does, indeed, work out for me. 

In case it's not something already on the schedule for those fixes you mention to do with apostrophes, one other issue, which certainly seems less simple to resolve, is that of proper nouns containing apostrophes - case in point, my own surname:

```
var posTagger = require("wink-pos-tagger");

var tagger = posTagger();

tagger.updateLexicon({
"O'Kelly": ['NNP']
});

tagger.tagSentence("My name is Chris O'Kelly");
// Returns:
//[{normal: "my", pos: "PRP$", tag: "word", value: "My"}
// {lemma: "name", normal: "name", pos: "NN", tag: "word", value: "name"}
// {lemma: "be", normal: "is", pos: "VBZ", tag: "word", value: "is"}
// {lemma: "chris", normal: "chris", pos: "NNS", tag: "word", value: "Chris"}
// {lemma: "o", normal: "o", pos: "NN", tag: "word", value: "O"}
// {lemma: "'ke", normal: "'ke", pos: "NN", tag: "word", value: "'Ke"}
// {normal: "lly", pos: "RB", tag: "word", value: "lly"}]
```

Note that this is the case even when I provide the `updateLexicon()` call, I assume because the tokenization is done before the tagger does anything. I do have a list of (mainly Scottish and Irish) common surnames that contain apostrophes, which I already have to use for some other libraries I integrate that have similar issues with handling them, but I'm not sure there is an easy fix for this in the case of Wink.

For what it's worth, these names do predominately follow the pattern `/O'[A-Z]?[a-z]+/`, if that helps at all

**Comment by rachnachakraborty** [comment]
We are delighted to learn that the workaround solved your problem.

We are in the process of releasing a comprehensive NLP package by June 2018 and were planning to club suggested fixes in the upcoming release. 

Looking at your need, we will release these changes **shortly** in the current package itself. 

Shall keep you posted on the release.

Have a great weekend!

**Comment by rachnachakraborty** [comment]
Hello @chris-divvito 

We are happy to share that, wink-pos-tagger ver 1.5.0 has been released to address the requirements highlighted.

Here is how it works:
```javascript
var posTagger = require("wink-pos-tagger");
var tagger = posTagger();

console.log( tagger.tagSentence( 'My name is Chris O\'Kelly' ) );
console.log( tagger.tagSentence( 'Then\'s the time to time the time flies' ) );
console.log( tagger.tagSentence( 'This is Michelle\'s food.' ) );
console.log( tagger.tagSentence( 'I won\'t believe you.' ) );
```
and the output is 

```javascript
[ { value: 'My', tag: 'word', normal: 'my', pos: 'PRP$' },
 { value: 'name', tag: 'word', normal: 'name', pos: 'NN', lemma: 'name' },
 { value: 'is', tag: 'word', normal: 'is', pos: 'VBZ', lemma: 'be' },
 { value: 'Chris', tag: 'word', normal: 'chris', pos: 'NNP' },
 { value: 'O\'Kelly', tag: 'word', normal: 'o\'kelly', pos: 'NNP' } ]

[ { value: 'Then', tag: 'word', normal: 'then', pos: 'RB' },
 { value: '\'s', tag: 'word', normal: '\'s', pos: 'VBZ', lemma: 'be' },
 { value: 'the', tag: 'word', normal: 'the', pos: 'DT' },
 { value: 'time', tag: 'word', normal: 'time', pos: 'NN', lemma: 'time' },
 { value: 'to', tag: 'word', normal: 'to', pos: 'TO' },
 { value: 'time', tag: 'word', normal: 'time', pos: 'VB', lemma: 'time' },
 { value: 'the', tag: 'word', normal: 'the', pos: 'DT' },
 { value: 'time', tag: 'word', normal: 'time', pos: 'NN', lemma: 'time' },
 { value: 'flies', tag: 'word', normal: 'flies', pos: 'VBZ', lemma: 'fly' } ]

[ { value: 'This', tag: 'word', normal: 'this', pos: 'DT' },
 { value: 'is', tag: 'word', normal: 'is', pos: 'VBZ', lemma: 'be' },
 { value: 'Michelle', tag: 'word', normal: 'michelle', pos: 'NNP' },
 { value: '\'s', tag: 'word', normal: '\'s', pos: 'POS' },
 { value: 'food', tag: 'word', normal: 'food', pos: 'NN', lemma: 'food' },
 { value: '.', tag: 'punctuation', normal: '.', pos: '.' } ]

[ { value: 'I', tag: 'word', normal: 'i', pos: 'PRP' },
 { value: 'wo', tag: 'word', normal: 'wo', pos: 'MD', lemma: 'will' },
 { value: 'n\'t', tag: 'word', normal: 'n\'t', pos: 'RB', lemma: 'not' },
 { value: 'believe', tag: 'word', normal: 'believe', pos: 'VB', lemma: 'believe' },
 { value: 'you', tag: 'word', normal: 'you', pos: 'PRP' },
 { value: '.', tag: 'punctuation', normal: '.', pos: '.' } ]
```
You will notice that  `updateLexicon()` api is not required in this case, as the tagger has now improved upon its NNP detection capabilities. However, exceptions will still need the `updateLexicon()` api.

Hope it works for you.

Best,

**Comment by sanjayaksaxena** [comment]
Hello @chris-divvito

Hope this version has addressed all the issues that you have discussed in this thread.

We are closing the issue for now.

If you have any further questions, feel free to get in touch.

Best,
Sanjaya

**Comment by ziaenezhad** [comment]
Hi,

I still have an issue with contractions. when I try this on `2.2.1`:
```javascript
/* eslint-disable no-console */

// Load wink-pos-tagger.
var posTagger = require( 'wink-pos-tagger' );

// Create an instance of the pos tagger.
var tagger = posTagger();

// Tag the sentence using the tag sentence api.
var tokens = tagger.tagSentence( "That's great !" );

console.log( tokens );
```
I'm getting:
```javascript
[
{normal: "that", pos: "IN", tag: "word", value: "That"},
{lemma: "'s", normal: "'s", pos: "NNS", tag: "word", value: "'s"},
{lemma: "great", normal: "great", pos: "JJ", tag: "word", value: "great"},
{normal: "!", pos: ".", tag: "punctuation", value: "!"}
]
```
https://runkit.com/embed/t59hm6ax2jlu

**Comment by sanjayaksaxena** [comment]
Hi @sajjad-shirazy 

Thanks for highlighting the issue.

Looks like the possible POS Tags for `'s` included `NNS`, which was causing `'s` to be tagged as NNS as a result of some transformation rule. This has been fixed in `wink-lexicon` and its dependency has been updated here accordingly; and a new patch version – 2.2.2 has been released.

Best,
Sanjaya
