### ISSUE TITLE
Feature request: user-defined rules

### ISSUE THREAD

**Issue by jenni-divvito** [winkjs/wink-pos-tagger#25]
Hey guys,

Thanks a bunch for the work you've done on this plugin. Just dropping by with a feature request that I would find quite helpful: 

Right now we can use updateLexicon to define specific string literals to match to tags. I recently came up against a problem because the solution I am building with wink-pos runs benchmarks against the Penn treebank. Wink-pos treats initials (like "**J.P.** Morgan", or "**H.R.** Puffenstuff") as multiple single letter NNP's separated by punctuation, which makes sense to me, but is different from the way the Penn treebank treats them, which is as a single NNP including the letters and punctuation.

It would be awesome if I could define Regexp matchers in updateLexicon, such that I could have something like: `/[A-Z]\.?(?:[A-Z]\.?)?/` map to a single NNP. Looking at the code, however, I can see how that would be a non-trivial change (for a start, they could not be used as keys into the lexicon object, and I don't know how well that would play with your tokenizer, etc).

Alternately, would it be possible to pass user-defined rules to the tagger() constructor in the same format as are consumed by the wink rules-engine? Right now I am post-processing the results from wink in order to condense these tags, but it feels like a bit of a wonky workaround, and it is fragile to any future changes.

If either of these are features you'd be happy to see in your library, I should be able to devote a little time to a pull request for them some time soon, but don't want to waste time making something that doesn't fit your vision for the library.

**Comment by rachnachakraborty** [comment]
@chris-divvito your requirement is very pertinent and definitely in our roadmap. Our plan is to address such requirements using [wink-ner](https://www.npmjs.com/package/wink-ner), the Named Entity Recognition tool; and coincidentally we have released its first stable version few days ago. 

You may also notice the open issue #21 here for `wink-ner` integration with the `wink-pos-tagger`. The example cited in [Getting Started](https://www.npmjs.com/package/wink-ner#getting-started) section should give you a glimpse of its features. You will be able to train it with entities of your interest.

Subsequently, we plan to incrementally add pre-trained common entities like countries, cities, popular places, people, organizations and more. These will evolve over a period of time. 

Please note, the current documentation of `wink-ner` does not expose the `wink-pos-tagger` integration features.

We should be in a position to release the integrated piece in a weeks' time.  Shall keep you posted!

Best,
Rachna

**Comment by jenni-divvito** [comment]
Oh awesome, I hadn't seen `wink-ner` yet, will go have a gander. Sorry if it seems like I'm flooding your issue board, it's only because it's such a useful tool that I'm getting significant use out of it.

**Comment by rachnachakraborty** [comment]
@chris-divvito, users like yourself are a delight for us :-)

**Comment by sanjayaksaxena** [comment]
Hi @chris-divvito 

Hope you have had a chance to look at wink-ner. We have updated the documentation of `wink-ner` to reflect its integration with the pos tagger. The documentation has an [example](http://winkjs.org/wink-ner/#getting-started), that you may like to checkout.

Hope this addresses your requirements now.

Best,
Sanjaya

**Comment by sanjayaksaxena** [comment]
Hi @chris-divvito, closing the issue for now... please get in touch if you need further assistance.
