### ISSUE TITLE
Chunking (identifying phrases?)

### ISSUE THREAD

**Issue by giorgio79** [winkjs/wink-pos-tagger#28]
Apache OpenNLP had a nice chunker that correctly identified noun and verb phrases. Any plans for chunking?
https://opennlp.apache.org/docs/1.8.4/manual/opennlp.html#tools.chunker

**Comment by sanjayaksaxena** [comment]
Hi @giorgio79 

Yes, we do have it on our immediate roadmap. Plan to add in 2-phase — start with a CYK/Rule-based one and subsequently release a ML driven one along with models for English/Hindi languages.

Expect the first one to get released in 4-6 weeks time!

Hope it answers your question.

Best,
Sanjaya

**Comment by giorgio79** [comment]
Fantastic! I recommend adding the phrase info as an additional feature to pos tagging, sg like this

```
var winkPosTagger = require("wink-pos-tagger")

// Create an instance of the pos tagger.
var tagger = winkPosTagger();

// Tag the sentence using the tag sentence api.
tagger.tagSentence( 'I have been to the United States of America.' );

Array (10 items)
0: Object {normal: "i", pos: "PRP", tag: "word", value: "I", phrase : "Noun", phrase_length : "1" , phrase_start: 1 , phrase_end: 1}
1: Object {lemma: "have", normal: "have", pos: "VBP", tag: "word", phrase : "Verb", phrase_length : "2", phrase_start: 1}
2: Object {lemma: "be", normal: "been", pos: "VBN", tag: "word",  phrase : "Verb", phrase_length : "2", phrase_end: 1}
3: Object {normal: "to", pos: "TO", tag: "word", value: "to",  phrase : "Noun" , phrase_length : "6", phrase_start: 1}
4: Object {normal: "the", pos: "DT", tag: "word", value: "the",  phrase : "Noun", phrase_length : "6"}
5: Object {lemma: "unite", normal: "united", pos: "VBN", tag: "word", phrase : "Noun", phrase_length : "6"}
6: Object {lemma: "state", normal: "states", pos: "NNS", tag: "word", phrase : "Noun", phrase_length : "6"}
7: Object {normal: "of", pos: "IN", tag: "word", value: "of",  phrase : "Noun" , phrase_length : "6"}
8: Object {normal: "america", pos: "NNP", tag: "word", value: "America",  phrase : "Noun", phrase_length : "6", phrase_end: 1}
9: Object {normal: ".", pos: ".", tag: "punctuation", value: "."}
Array Prototype
```

**Comment by sanjayaksaxena** [comment]
Hi @giorgio79 

We have moved this for our next release of NLP. Will update you here once it is released.

Best,
Sanjaya

**Comment by tsortwehttam** [comment]
I'm really happy to hear that you plan to release a CYK parser  🎉

Will it include dependency annotations (like `NSUBJ`)? Or phrase structure annotations (like `VP`)?

**Comment by sanjayaksaxena** [comment]
Thank you for sharing your excitement with us. Such words are a force multiplier for us. We are striving to release a mature NLP package, which will be based on the state-of-the-art. It should begin to unfold in a few weeks. 

To begin with, it will have phrase structure annotation. One of the challenge is to find a suitable training corpus, under an open source friendly license!

We will keep you posted.

**Comment by DawsonMacPhee** [comment]
Did this ever actually get implemented? If so, where can I find the docs?

**Comment by sanjayaksaxena** [comment]
Hello @matthewtoast 

Due to certain other priorities, this has not been implemented yet. 

In the mean time you may like to explore [wink-nlp](https://github.com/winkjs/wink-nlp). This has provision for [custom entity detection](https://winkjs.org/wink-nlp/custom-entities.html), here you will find simple inspirations to extract noun & verb phrases easily; yet this far away from being a parser.

We will surely update you whenever it released.
