### ISSUE TITLE
Accuracy on the Penn Treebank test?

### ISSUE THREAD

**Issue by giorgio79** [winkjs/wink-pos-tagger#29]
Javascript based en-pos is quite good https://www.npmjs.com/package/en-pos
Have you measured the accuracy?

**Comment by rachnachakraborty** [comment]
Hi @giorgio79,

The user community have bench-marked `wink-pos-tagger`. For example, the issue of Feature request: user-defined rules #25

We have been informally measuring the accuracy and found it to be promising.

Thanks,
Rachna

**Comment by sanjayaksaxena** [comment]
Hi @giorgio79 

Recently we ran a benchmark using the standard WSJ22-24 dataset – `wink-pos-tagger` delivers an accuracy of **93.2%** at ≥**525,000 tokens/second** speed. The benchmark was carried out on 2.2 GHz Intel Core i7 machine with 16GB RAM.

Thanks for your query.

Best,
Sanjaya
