### ISSUE TITLE
Incorrect tagging of double contractions like "you'll've"

### ISSUE THREAD

**Issue by tsortwehttam** [winkjs/wink-pos-tagger#37]
This is definitely an edge case, but one you might want to know about.

When given this input:

    "you'll've"

(a contraction of `"you will have"`)

The output is:

    [ { value: 'you\'ll\'ve',
          tag: 'word',
          normal: 'you\'ll\'ve',
          pos: 'NNP',
          lemma: 'you\'ll\'ve' } ]

I would expect these to be individuized into three tokens.

Again, this is an edge case, but for comparison, SpaCy is able to handle this fine.

**Comment by rachnachakraborty** [comment]
Hi @matthewtoast 

Thanks for highlighting the edge-cases.  We have added commonly used such contractions and released a new version 2.2.0.

Hope this helps.

We are working on a major release with more features. Shall keep you posted.

Best,
Rachna
