### ISSUE TITLE
Incorect PoS detection for *ing words

### ISSUE THREAD

**Issue by pavelmn** [winkjs/wink-pos-tagger#42]
"See the following section."
Actual result:
following is verd
{lemma: "follow", normal: "following", pos: "VBG", tag: "word", value: "following"}

Expected result:
following should be adjective. See for the reference:
https://en.wiktionary.org/wiki/following

**Comment by sanjayaksaxena** [comment]
Hello @pavelmn 

Thanks for the input.

The `wink-pos-tagger` provides an [`updateLexicon()`](https://winkjs.org/wink-pos-tagger/Tagger.html#updateLexicon) API, which may be used to address this issue.

As such with 93.2% accuracy against the standard WSJ data, one is expected to experience such issues plus the accuracy also a function of vocabulary and the transformation rules learned from the annotated data!

Hope it helps.

Best,
Sanjaya
