### ISSUE TITLE
Can we send an empty pos field if not a proper English word(if it doesn't belong to English parts of speech)?

### ISSUE THREAD

**Issue by DineshMadanlal** [winkjs/wink-pos-tagger#45]
```
// Load wink-pos-tagger.
const posTagger = require( 'wink-pos-tagger' );
// Create an instance of the pos tagger.
let tagger = posTagger();

// Tag the sentence using the tag sentence api.
const result = tagger.tagSentence( 'oqoaoiosnn' );
console.log('the result is', result);
```

Please correct me if I am wrong. `oqoaoiosnn` is not a part of POS. If that's the case, can we send an empty pos field({ pos: '' })?

**Comment by sanjayaksaxena** [comment]
Such words are called unseen or out of vocabulary (OOV) words. Here "vocabulary" means the collection of words that the pos tagger has seen during its training and not the universe of entire language (in our case English). Typically a pos tagger attempts to pos tag an OOV word by looking at its context and or features such as suffix — for example if the word ends with an -ing suffix, it may get tagged as VBG. Finally if everything fails then the word gets tagged as noun or proper noun.

In our case also the tagger follows the same behavior and attempt to tag it based on its features/context — it will never leave the pos tag empty.
